/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package chessgameclient;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;
import javax.swing.JPanel;

/**
 *
 * @author T4g1
 */
public class GameGUI extends javax.swing.JFrame {
    private static final int GRID_WIDTH = 8;
    private static final int GRID_HEIGHT = 8;
    
    private CaseGUI[][] l_case = new CaseGUI[GRID_WIDTH][GRID_HEIGHT];
    private JPanel echiquier = new JPanel(
            new GridLayout(GRID_WIDTH, GRID_HEIGHT));
    
    //<editor-fold defaultstate="collapsed" desc="Constructeurs">
    
    /**
     * Initialise la grille de jeu
     */
    public GameGUI(){
        // Crée toutes les cases du jeu
        for(int x=0; x<GRID_WIDTH; x++)
        {
            for(int y=0; y<GRID_HEIGHT; y++)
            {
                // Donne la position de la case a cette derniére
                l_case[x][y] = new CaseGUI(x, y);
                
                // Modifie la couleur de la case
                if((x + y) % 2 == 0)
                {
                    l_case[x][y].setBackground(Color.WHITE);
                }
                else
                {
                    l_case[x][y].setBackground(Color.BLACK);
                }
        
                // AJoute la case sur l'échéquier
                echiquier.add(l_case[x][y]);
            }
        }
        
        // Ajoute l'échiquier dans la fenêtre
        add(echiquier);
        
        // Modifie les dimensions de la fenêtre
        Dimension window_size = new Dimension();
        window_size.width = GRID_WIDTH * CaseGUI.getCaseWidth();
        window_size.height = GRID_HEIGHT * CaseGUI.getCaseHeight();
        
        setSize(window_size);
        setResizable(false);
    }
    
    //</editor-fold>

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
