/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Applet;

import java.text.DateFormat;
import java.util.Date;
import java.util.TimeZone;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author delskev
 */
public class DisplayDate extends javax.swing.JPanel implements Runnable {

    
    private Date dateHeure;
    private String myDate;
    private int pause;
    private String pays;
    /**
     * Creates new form DisplayDate
     */
    public DisplayDate() {
        initComponents();
        
        dateHeure = new Date();
        setPays("Europe/Brussels");
        TimeZone pstTime = TimeZone.getTimeZone("Europe/Brussels");
        DateFormat df = DateFormat.getTimeInstance(DateFormat.DEFAULT); 
        setMyDate(df.format(dateHeure));
    }

    public DisplayDate(String zone) {
        initComponents();
        
        dateHeure = new Date();
        TimeZone pstTime = TimeZone.getTimeZone(zone);
        DateFormat df = DateFormat.getTimeInstance(DateFormat.DEFAULT); 
        setMyDate(df.format(dateHeure));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        display = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        display.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(display, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(display)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel display;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        try {
            while(true){
                dateHeure = new Date();
                TimeZone pstTime = TimeZone.getTimeZone(getPays());
                DateFormat df = DateFormat.getTimeInstance(DateFormat.DEFAULT); 
                df.setTimeZone(pstTime);
                setMyDate(df.format(dateHeure));
                
                display.setText(myDate);
                Thread.sleep(pause*1000);
            }
        } catch (InterruptedException ex) {
                Logger.getLogger(DisplayDate.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    //<editor-fold defaultstate="collapsed" desc="get and set">
    
    
    /**
     * @return the dateHeure
     */
    public Date getDateHeure() {
        return dateHeure;
    }

    /**
     * @param dateHeure the dateHeure to set
     */
    public void setDateHeure(Date dateHeure) {
        this.dateHeure = dateHeure;
    }

    /**
     * @return the myDate
     */
    public String getMyDate() {
        return myDate;
    }

    /**
     * @param myDate the myDate to set
     */
    public void setMyDate(String myDate) {
        this.myDate = myDate;
    }

    /**
     * @return the pause
     */
    public int getPause() {
        return pause;
    }

    /**
     * @param pause the pause to set
     */
    public void setPause(int pause) {
        this.pause = pause;
    }

    /**
     * @return the pays
     */
    public String getPays() {
        return pays;
    }

    /**
     * @param pays the pays to set
     */
    public void setPays(String pays) {
        this.pays = pays;
    }

    /**
     * @return the jLabel1
     */
    public javax.swing.JLabel getjLabel1() {
        return display;
    }

    /**
     * @param jLabel1 the jLabel1 to set
     */
    public void setjLabel1(javax.swing.JLabel jLabel1) {
        this.display = jLabel1;
    }
    //</editor-fold>
    
}
