//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientServiceWeb.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Session/", ConfigurationName="ServiceReference1.SOAPWS")]
    public interface SOAPWS {
        
        // CODEGEN: Generating message contract since the operation AddPlayer is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://Session/SOAPWS/AddPlayerRequest", ReplyAction="http://Session/SOAPWS/AddPlayerResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ClientServiceWeb.ServiceReference1.AddPlayerResponse1 AddPlayer(ClientServiceWeb.ServiceReference1.AddPlayerRequest request);
        
        // CODEGEN: Generating message contract since the operation GetPlayer is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://Session/SOAPWS/GetPlayerRequest", ReplyAction="http://Session/SOAPWS/GetPlayerResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ClientServiceWeb.ServiceReference1.GetPlayerResponse GetPlayer(ClientServiceWeb.ServiceReference1.GetPlayerRequest request);
        
        // CODEGEN: Generating message contract since the operation AlterUser is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://Session/SOAPWS/AlterUserRequest", ReplyAction="http://Session/SOAPWS/AlterUserResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ClientServiceWeb.ServiceReference1.AlterUserResponse1 AlterUser(ClientServiceWeb.ServiceReference1.AlterUserRequest request);
        
        // CODEGEN: Generating message contract since the operation RemovePlayer is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://Session/SOAPWS/RemovePlayerRequest", ReplyAction="http://Session/SOAPWS/RemovePlayerResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ClientServiceWeb.ServiceReference1.RemovePlayerResponse1 RemovePlayer(ClientServiceWeb.ServiceReference1.RemovePlayerRequest request);
        
        // CODEGEN: Generating message contract since the operation getHighScore is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://Session/SOAPWS/getHighScoreRequest", ReplyAction="http://Session/SOAPWS/getHighScoreResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ClientServiceWeb.ServiceReference1.getHighScoreResponse getHighScore(ClientServiceWeb.ServiceReference1.getHighScoreRequest request);
        
        // CODEGEN: Generating message contract since the operation GetPlayByPlayer is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://Session/SOAPWS/GetPlayByPlayerRequest", ReplyAction="http://Session/SOAPWS/GetPlayByPlayerResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ClientServiceWeb.ServiceReference1.GetPlayByPlayerResponse GetPlayByPlayer(ClientServiceWeb.ServiceReference1.GetPlayByPlayerRequest request);
        
        // CODEGEN: Generating message contract since the operation GetLooseByPlayer is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://Session/SOAPWS/GetLooseByPlayerRequest", ReplyAction="http://Session/SOAPWS/GetLooseByPlayerResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ClientServiceWeb.ServiceReference1.GetLooseByPlayerResponse GetLooseByPlayer(ClientServiceWeb.ServiceReference1.GetLooseByPlayerRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Session/")]
    public partial class AddPlayer : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string pseudoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string pseudo {
            get {
                return this.pseudoField;
            }
            set {
                this.pseudoField = value;
                this.RaisePropertyChanged("pseudo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Session/")]
    public partial class GetLooseByPlayer : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Session/")]
    public partial class GetPlayByPlayer : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Session/")]
    public partial class highScore : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string pseudoField;
        
        private long scoreField;
        
        private bool scoreFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string pseudo {
            get {
                return this.pseudoField;
            }
            set {
                this.pseudoField = value;
                this.RaisePropertyChanged("pseudo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long score {
            get {
                return this.scoreField;
            }
            set {
                this.scoreField = value;
                this.RaisePropertyChanged("score");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool scoreSpecified {
            get {
                return this.scoreFieldSpecified;
            }
            set {
                this.scoreFieldSpecified = value;
                this.RaisePropertyChanged("scoreSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Session/")]
    public partial class getHighScore : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Session/")]
    public partial class RemovePlayerResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Session/")]
    public partial class RemovePlayer : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Session/")]
    public partial class AlterUserResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Session/")]
    public partial class AlterUser : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idField;
        
        private string pseudoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string pseudo {
            get {
                return this.pseudoField;
            }
            set {
                this.pseudoField = value;
                this.RaisePropertyChanged("pseudo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Session/")]
    public partial class joueur : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idField;
        
        private bool idFieldSpecified;
        
        private string pseudoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string pseudo {
            get {
                return this.pseudoField;
            }
            set {
                this.pseudoField = value;
                this.RaisePropertyChanged("pseudo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Session/")]
    public partial class GetPlayer : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Session/")]
    public partial class AddPlayerResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddPlayerRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://Session/")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string username;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://Session/")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Session/", Order=0)]
        public ClientServiceWeb.ServiceReference1.AddPlayer AddPlayer;
        
        public AddPlayerRequest() {
        }
        
        public AddPlayerRequest(string username, string password, ClientServiceWeb.ServiceReference1.AddPlayer AddPlayer) {
            this.username = username;
            this.password = password;
            this.AddPlayer = AddPlayer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddPlayerResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Session/", Order=0)]
        public ClientServiceWeb.ServiceReference1.AddPlayerResponse AddPlayerResponse;
        
        public AddPlayerResponse1() {
        }
        
        public AddPlayerResponse1(ClientServiceWeb.ServiceReference1.AddPlayerResponse AddPlayerResponse) {
            this.AddPlayerResponse = AddPlayerResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPlayerRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://Session/")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string username;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://Session/")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Session/", Order=0)]
        public ClientServiceWeb.ServiceReference1.GetPlayer GetPlayer;
        
        public GetPlayerRequest() {
        }
        
        public GetPlayerRequest(string username, string password, ClientServiceWeb.ServiceReference1.GetPlayer GetPlayer) {
            this.username = username;
            this.password = password;
            this.GetPlayer = GetPlayer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPlayerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPlayerResponse", Namespace="http://Session/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public joueur[] GetPlayerResponse1;
        
        public GetPlayerResponse() {
        }
        
        public GetPlayerResponse(joueur[] GetPlayerResponse1) {
            this.GetPlayerResponse1 = GetPlayerResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AlterUserRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://Session/")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string username;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://Session/")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Session/", Order=0)]
        public ClientServiceWeb.ServiceReference1.AlterUser AlterUser;
        
        public AlterUserRequest() {
        }
        
        public AlterUserRequest(string username, string password, ClientServiceWeb.ServiceReference1.AlterUser AlterUser) {
            this.username = username;
            this.password = password;
            this.AlterUser = AlterUser;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AlterUserResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Session/", Order=0)]
        public ClientServiceWeb.ServiceReference1.AlterUserResponse AlterUserResponse;
        
        public AlterUserResponse1() {
        }
        
        public AlterUserResponse1(ClientServiceWeb.ServiceReference1.AlterUserResponse AlterUserResponse) {
            this.AlterUserResponse = AlterUserResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemovePlayerRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://Session/")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string username;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://Session/")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Session/", Order=0)]
        public ClientServiceWeb.ServiceReference1.RemovePlayer RemovePlayer;
        
        public RemovePlayerRequest() {
        }
        
        public RemovePlayerRequest(string username, string password, ClientServiceWeb.ServiceReference1.RemovePlayer RemovePlayer) {
            this.username = username;
            this.password = password;
            this.RemovePlayer = RemovePlayer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemovePlayerResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Session/", Order=0)]
        public ClientServiceWeb.ServiceReference1.RemovePlayerResponse RemovePlayerResponse;
        
        public RemovePlayerResponse1() {
        }
        
        public RemovePlayerResponse1(ClientServiceWeb.ServiceReference1.RemovePlayerResponse RemovePlayerResponse) {
            this.RemovePlayerResponse = RemovePlayerResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getHighScoreRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://Session/")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string username;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://Session/")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Session/", Order=0)]
        public ClientServiceWeb.ServiceReference1.getHighScore getHighScore;
        
        public getHighScoreRequest() {
        }
        
        public getHighScoreRequest(string username, string password, ClientServiceWeb.ServiceReference1.getHighScore getHighScore) {
            this.username = username;
            this.password = password;
            this.getHighScore = getHighScore;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getHighScoreResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getHighScoreResponse", Namespace="http://Session/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public highScore[] getHighScoreResponse1;
        
        public getHighScoreResponse() {
        }
        
        public getHighScoreResponse(highScore[] getHighScoreResponse1) {
            this.getHighScoreResponse1 = getHighScoreResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPlayByPlayerRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://Session/")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string username;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://Session/")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Session/", Order=0)]
        public ClientServiceWeb.ServiceReference1.GetPlayByPlayer GetPlayByPlayer;
        
        public GetPlayByPlayerRequest() {
        }
        
        public GetPlayByPlayerRequest(string username, string password, ClientServiceWeb.ServiceReference1.GetPlayByPlayer GetPlayByPlayer) {
            this.username = username;
            this.password = password;
            this.GetPlayByPlayer = GetPlayByPlayer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPlayByPlayerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPlayByPlayerResponse", Namespace="http://Session/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public highScore[] GetPlayByPlayerResponse1;
        
        public GetPlayByPlayerResponse() {
        }
        
        public GetPlayByPlayerResponse(highScore[] GetPlayByPlayerResponse1) {
            this.GetPlayByPlayerResponse1 = GetPlayByPlayerResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLooseByPlayerRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://Session/")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string username;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://Session/")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Session/", Order=0)]
        public ClientServiceWeb.ServiceReference1.GetLooseByPlayer GetLooseByPlayer;
        
        public GetLooseByPlayerRequest() {
        }
        
        public GetLooseByPlayerRequest(string username, string password, ClientServiceWeb.ServiceReference1.GetLooseByPlayer GetLooseByPlayer) {
            this.username = username;
            this.password = password;
            this.GetLooseByPlayer = GetLooseByPlayer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLooseByPlayerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLooseByPlayerResponse", Namespace="http://Session/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public highScore[] GetLooseByPlayerResponse1;
        
        public GetLooseByPlayerResponse() {
        }
        
        public GetLooseByPlayerResponse(highScore[] GetLooseByPlayerResponse1) {
            this.GetLooseByPlayerResponse1 = GetLooseByPlayerResponse1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SOAPWSChannel : ClientServiceWeb.ServiceReference1.SOAPWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SOAPWSClient : System.ServiceModel.ClientBase<ClientServiceWeb.ServiceReference1.SOAPWS>, ClientServiceWeb.ServiceReference1.SOAPWS {
        
        public SOAPWSClient() {
        }
        
        public SOAPWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SOAPWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SOAPWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SOAPWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientServiceWeb.ServiceReference1.AddPlayerResponse1 ClientServiceWeb.ServiceReference1.SOAPWS.AddPlayer(ClientServiceWeb.ServiceReference1.AddPlayerRequest request) {
            return base.Channel.AddPlayer(request);
        }
        
        public ClientServiceWeb.ServiceReference1.AddPlayerResponse AddPlayer(string username, string password, ClientServiceWeb.ServiceReference1.AddPlayer AddPlayer1) {
            ClientServiceWeb.ServiceReference1.AddPlayerRequest inValue = new ClientServiceWeb.ServiceReference1.AddPlayerRequest();
            inValue.username = username;
            inValue.password = password;
            inValue.AddPlayer = AddPlayer1;
            ClientServiceWeb.ServiceReference1.AddPlayerResponse1 retVal = ((ClientServiceWeb.ServiceReference1.SOAPWS)(this)).AddPlayer(inValue);
            return retVal.AddPlayerResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientServiceWeb.ServiceReference1.GetPlayerResponse ClientServiceWeb.ServiceReference1.SOAPWS.GetPlayer(ClientServiceWeb.ServiceReference1.GetPlayerRequest request) {
            return base.Channel.GetPlayer(request);
        }
        
        public joueur[] GetPlayer(string username, string password, ClientServiceWeb.ServiceReference1.GetPlayer GetPlayer1) {
            ClientServiceWeb.ServiceReference1.GetPlayerRequest inValue = new ClientServiceWeb.ServiceReference1.GetPlayerRequest();
            inValue.username = username;
            inValue.password = password;
            inValue.GetPlayer = GetPlayer1;
            ClientServiceWeb.ServiceReference1.GetPlayerResponse retVal = ((ClientServiceWeb.ServiceReference1.SOAPWS)(this)).GetPlayer(inValue);
            return retVal.GetPlayerResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientServiceWeb.ServiceReference1.AlterUserResponse1 ClientServiceWeb.ServiceReference1.SOAPWS.AlterUser(ClientServiceWeb.ServiceReference1.AlterUserRequest request) {
            return base.Channel.AlterUser(request);
        }
        
        public ClientServiceWeb.ServiceReference1.AlterUserResponse AlterUser(string username, string password, ClientServiceWeb.ServiceReference1.AlterUser AlterUser1) {
            ClientServiceWeb.ServiceReference1.AlterUserRequest inValue = new ClientServiceWeb.ServiceReference1.AlterUserRequest();
            inValue.username = username;
            inValue.password = password;
            inValue.AlterUser = AlterUser1;
            ClientServiceWeb.ServiceReference1.AlterUserResponse1 retVal = ((ClientServiceWeb.ServiceReference1.SOAPWS)(this)).AlterUser(inValue);
            return retVal.AlterUserResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientServiceWeb.ServiceReference1.RemovePlayerResponse1 ClientServiceWeb.ServiceReference1.SOAPWS.RemovePlayer(ClientServiceWeb.ServiceReference1.RemovePlayerRequest request) {
            return base.Channel.RemovePlayer(request);
        }
        
        public ClientServiceWeb.ServiceReference1.RemovePlayerResponse RemovePlayer(string username, string password, ClientServiceWeb.ServiceReference1.RemovePlayer RemovePlayer1) {
            ClientServiceWeb.ServiceReference1.RemovePlayerRequest inValue = new ClientServiceWeb.ServiceReference1.RemovePlayerRequest();
            inValue.username = username;
            inValue.password = password;
            inValue.RemovePlayer = RemovePlayer1;
            ClientServiceWeb.ServiceReference1.RemovePlayerResponse1 retVal = ((ClientServiceWeb.ServiceReference1.SOAPWS)(this)).RemovePlayer(inValue);
            return retVal.RemovePlayerResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientServiceWeb.ServiceReference1.getHighScoreResponse ClientServiceWeb.ServiceReference1.SOAPWS.getHighScore(ClientServiceWeb.ServiceReference1.getHighScoreRequest request) {
            return base.Channel.getHighScore(request);
        }
        
        public highScore[] getHighScore(string username, string password, ClientServiceWeb.ServiceReference1.getHighScore getHighScore1) {
            ClientServiceWeb.ServiceReference1.getHighScoreRequest inValue = new ClientServiceWeb.ServiceReference1.getHighScoreRequest();
            inValue.username = username;
            inValue.password = password;
            inValue.getHighScore = getHighScore1;
            ClientServiceWeb.ServiceReference1.getHighScoreResponse retVal = ((ClientServiceWeb.ServiceReference1.SOAPWS)(this)).getHighScore(inValue);
            return retVal.getHighScoreResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientServiceWeb.ServiceReference1.GetPlayByPlayerResponse ClientServiceWeb.ServiceReference1.SOAPWS.GetPlayByPlayer(ClientServiceWeb.ServiceReference1.GetPlayByPlayerRequest request) {
            return base.Channel.GetPlayByPlayer(request);
        }
        
        public highScore[] GetPlayByPlayer(string username, string password, ClientServiceWeb.ServiceReference1.GetPlayByPlayer GetPlayByPlayer1) {
            ClientServiceWeb.ServiceReference1.GetPlayByPlayerRequest inValue = new ClientServiceWeb.ServiceReference1.GetPlayByPlayerRequest();
            inValue.username = username;
            inValue.password = password;
            inValue.GetPlayByPlayer = GetPlayByPlayer1;
            ClientServiceWeb.ServiceReference1.GetPlayByPlayerResponse retVal = ((ClientServiceWeb.ServiceReference1.SOAPWS)(this)).GetPlayByPlayer(inValue);
            return retVal.GetPlayByPlayerResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientServiceWeb.ServiceReference1.GetLooseByPlayerResponse ClientServiceWeb.ServiceReference1.SOAPWS.GetLooseByPlayer(ClientServiceWeb.ServiceReference1.GetLooseByPlayerRequest request) {
            return base.Channel.GetLooseByPlayer(request);
        }
        
        public highScore[] GetLooseByPlayer(string username, string password, ClientServiceWeb.ServiceReference1.GetLooseByPlayer GetLooseByPlayer1) {
            ClientServiceWeb.ServiceReference1.GetLooseByPlayerRequest inValue = new ClientServiceWeb.ServiceReference1.GetLooseByPlayerRequest();
            inValue.username = username;
            inValue.password = password;
            inValue.GetLooseByPlayer = GetLooseByPlayer1;
            ClientServiceWeb.ServiceReference1.GetLooseByPlayerResponse retVal = ((ClientServiceWeb.ServiceReference1.SOAPWS)(this)).GetLooseByPlayer(inValue);
            return retVal.GetLooseByPlayerResponse1;
        }
    }
}
